### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by DOFfactory** [aidewoode/black_candy#28]
Whenever I try to follow your commands, I receive the following error:

```
Creating black_candy_redis_1    ... done
Creating black_candy_postgres_1 ... done
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
make: *** [Makefile:38: production_setup] Error 1
```

Would it be possible to provide a full docker solution, and also instructions on the hub.docker.com website? Currently, cloning the image and then building is pretty complicated, and I do not reallt know where the error is.

In addition to this, I wonder whether this server provides also transcoding functionality? It is not obvious from the settings... Is it possible to implement it?

**Comment by aidewoode** [comment]
It seem like your network issue. Black candy already use pre builded image to setup server, it's just pull image down not for build whole image.
