### ISSUE TITLE
How do I make this run in docker?

### ISSUE THREAD

**Issue by hyphenrf** [aidewoode/black_candy#39]
So I pulled blackcandy/blackcandy from dockerhub. Then I did docker run with that name and with networking mapped to my host.
When I try to visit the app from the web frontend I get "An unhandled lowlevel error occurred. The application logs may have details."

When I checked the logs with docker I found the following:
```
Rack app error handling request { GET / }
#<ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`>
/usr/local/bundle/gems/railties-6.0.1/lib/rails/application.rb:580:in `validate_secret_key_base'
/usr/local/bundle/gems/railties-6.0.1/lib/rails/application.rb:423:in `secret_key_base'
/usr/local/bundle/gems/railties-6.0.1/lib/rails/application.rb:253:in `env_config'
/usr/local/bundle/gems/railties-6.0.1/lib/rails/engine.rb:720:in `build_request'
/usr/local/bundle/gems/railties-6.0.1/lib/rails/application.rb:603:in `build_request'
/usr/local/bundle/gems/railties-6.0.1/lib/rails/engine.rb:525:in `call'
/usr/local/bundle/gems/puma-4.2.1/lib/puma/configuration.rb:228:in `call'
/usr/local/bundle/gems/puma-4.2.1/lib/puma/server.rb:667:in `handle_request'
/usr/local/bundle/gems/puma-4.2.1/lib/puma/server.rb:470:in `process_client'
/usr/local/bundle/gems/puma-4.2.1/lib/puma/server.rb:328:in `block in run'
/usr/local/bundle/gems/puma-4.2.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```
so I'm guessing I set it up wrong (missing stuff). Namely secret_key_base which I assume should be fed to the app thru an env var. Still, which secret key to begin with? And what else is missing here?

**Comment by aidewoode** [comment]
Hi, you can't just pull blackcandy/blackcandy  image and run it.  Black candy need other sevices to running. You can follow the instruction on README to setup.
