### ISSUE TITLE
Demo: account credentials are wrong

### ISSUE THREAD

**Issue by murat** [aidewoode/black_candy#5]

**Comment by IgorPolyakov** [comment]
![Снимок экрана от 2019-07-05 13-00-02](https://user-images.githubusercontent.com/2613581/60715071-b9aba000-9f0b-11e9-80c2-28fb017186a1.png)

everything is working

**Comment by murat** [comment]
Sorry, I tried to log in with admin credentials. Wrong alarm.

**Comment by ogirginc** [comment]
When I try to login at http://178.62.101.174/session/new with `foo@bar.com` & `foobar`, keep getting "wrong e-mail or password" error. I copied & pasted both values to be sure but no luck. Any ideas?

**Comment by aidewoode** [comment]
@ogirginc maybe somebody change the password on demo, I have reset the password, you can try it.

**Comment by ogirginc** [comment]
Yep, it works now. Thanks.
