### ISSUE TITLE
Songs not playing

### ISSUE THREAD

**Issue by IgorPolyakov** [aidewoode/black_candy#6]
Browser: Firefox 69.0b1 (64-bit)

![image](https://user-images.githubusercontent.com/2613581/60715835-84a04d00-9f0d-11e9-8237-98ac062166c5.png)

In logs, prints this message
```
app_1       | X-Accel-Mapping header missing                                                                                                                                                                       
```

**Comment by aidewoode** [comment]
Hi, do you use the docker image to deploy? and what's the song format you playing?

**Comment by IgorPolyakov** [comment]
Hi) I try to play different songs, but some play and some not.
Format file is the same
```
# this song playing
$ file Обе-Рек\ -\ Сердце\ заставило.mp3 
Обе-Рек - Сердце заставило.mp3: Audio file with ID3 version 2.3.0, contains:MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo

# but this song is not playing
$ file 2019\ -\ Rammstein\ -\ RAMMSTEIN/04.\ AUSLÄNDER.mp3
2019 - Rammstein - RAMMSTEIN/04. AUSLÄNDER.mp3: Audio file with ID3 version 2.3.0, contains:MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo
```

I run it on my laptop
via  `docker-compose up -d`

**Comment by aidewoode** [comment]
It's so weird, can you send me your music file via email? so I can debug on my machine. My email address is `aidewoode@gmail.com`. Thank you.

**Comment by connor4312** [comment]
I'm also hitting this, deploying via the docker instructions.

**Comment by connor4312** [comment]
I feel smart. It was a file permissioning issue, at least for me 😛 

Looking at the code, it's pretty straightforward. I'd imagine Igor is running into some kind of similar permission on the files. Both are mp3's, so it should not be an issue with ffmpeg.

**Comment by aidewoode** [comment]
@IgorPolyakov 

Hi, I have test the file you send to me on firefox 69. It works fine. And I noticed your browser console say `Request to access cookie or storage on “<URL>” was blocked`, and response return `403(forbidden)`. Maybe you set your browser to block cookie on this site? Please check out your browser setting. Thank you.

**Comment by IgorPolyakov** [comment]
Sorry me , nginx haven't permission to read some music files.
I fix it and all work!
