### ISSUE TITLE
Artist Cover

### ISSUE THREAD

**Issue by reload-mb** [aidewoode/black_candy#63]
Congratulations for the wonderful project, I have one question
How can i set artists image manually?
I'm doing a personal streaming server for some music that me and my friends make, so there is no official image on discogs or similar sites. From your code I understand that artist images can be attached only via discogs.
Thanks for your time.

**Comment by aidewoode** [comment]
Sorry for the late reply. Black candy can't set artists image manually, cause it hasn't had this feature yet.  I will take some time to implement this feature. Thanks.

**Comment by reload-mb** [comment]
No rush,
I'm no expert in Ruby, but I can try to get my hands on.
Thanks
