### ISSUE TITLE
Support grouping by "Album Artist"

### ISSUE THREAD

**Issue by angerson** [aidewoode/black_candy#67]
Most of my albums are compilations grouped under one "Album Artist." A contrived example:

| Song | Artist | Album Artist |
|-|-|-|
| The Foo (qux remix) | qux | The Foo Remix Collective |
| The Foo (bar remix) | bar | The Foo Remix Collective |
| The Foo (bam remix) | bam | The Foo Remix Collective |

Currently Black Candy splits this into 3 albums in the Albums tab, one for each artist. I'd like to view my albums grouped by Album Artist. Some ideas:

- Add a "Group By..." setting to the Albums tab.
- Add a "Compilations" tab that's just like the Albums tab, except that it merges albums by Album Artist.

**Comment by aidewoode** [comment]
Black candy already had support for various artists album https://github.com/aidewoode/black_candy/commit/ad10ea99e6cc3e21322ebe2de82833e78e7cccef,  but this feature hasn't been released yet. And I still have a few issues to deal with and the new version will be released before the end of this month.

Thanks.
