### ISSUE TITLE
mtime rather than file hash for change detection

### ISSUE THREAD

**Issue by connor4312** [aidewoode/black_candy#8]
Currently [we hash](https://github.com/aidewoode/black_candy/blob/3701e440494db0f2b5d9e496e19f91f5d3dfe08d/app/models/media_file.rb#L92) the first 5MB of the file for uniqueness+to see if it's changed. This means that syncing can take a while and read a lot of data. I'm using Azure blob mounted via fuse, so reading 5MB from every single track ends up taking a lot of time.

Using the mtime to do the comparison would be a desirable option. In this case blobfuse would read the blob metadata, instead of downloading the file, which is pretty instant.  Perhaps a way to toggle between using mtime versus a hash would be appropriate if there's scenarios where a hash is more desirable, such as for deduplication.

I'm not much of a rubyist but I'm happy to try to PR this if there's interest. It seems like it should be a pretty easy point fix--we can create the hash in the linked method from a combination of the mtime and the file path rather than the file contents.

**Comment by aidewoode** [comment]
🤔 ,  I just can't remember why I use hash over mtime before. I just sit here about an hour to think about the situation I must use hash,  I hope I didn't miss something.  But I can't  find proper reason for it.  I think I did a bad decision before , use mtime and file path is better.

And PR is always welcome. Thank you.
